modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://github.com/deletey/compact-storage/issues"
[[mods]]
modId="compactstorage"
version="${file.jarVersion}"
displayName="Compact Storage"
updateJSONURL="http://tobystrong.me/compactstorage/version.json"
displayURL="http://tobystrong.me/compactstorage/"
logoFile="compactstorage.png"
credits="To all of the nice resoures that helped me figure out Forge again! Translations for Brazilian Portugese by Mikeliro"
authors="Toby Strong"
description='''
Bringing chests and backpacks of all sizes right to your Minecraft world
'''
[[dependencies.compactstorage]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compactstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
